/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Artist = IDL.Record({
  'id' : IDL.Nat,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'specialty' : IDL.Text,
});
export const Artwork = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Int,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'artist' : IDL.Text,
  'medium' : IDL.Text,
});
export const Time = IDL.Int;
export const Exhibition = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : Time,
});

export const idlService = IDL.Service({
  'addArtist' : IDL.Func([Artist], [IDL.Nat], []),
  'addArtwork' : IDL.Func([Artwork], [IDL.Nat], []),
  'addExhibition' : IDL.Func([Exhibition], [IDL.Nat], []),
  'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
  'getAllArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
  'getAllExhibitions' : IDL.Func([], [IDL.Vec(Exhibition)], ['query']),
  'getAllExhibitionsSortedByDate' : IDL.Func(
      [],
      [IDL.Vec(Exhibition)],
      ['query'],
    ),
  'getArtist' : IDL.Func([IDL.Nat], [Artist], ['query']),
  'getArtwork' : IDL.Func([IDL.Nat], [Artwork], ['query']),
  'getExhibition' : IDL.Func([IDL.Nat], [Exhibition], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Artist = IDL.Record({
    'id' : IDL.Nat,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'specialty' : IDL.Text,
  });
  const Artwork = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Int,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'artist' : IDL.Text,
    'medium' : IDL.Text,
  });
  const Time = IDL.Int;
  const Exhibition = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : Time,
  });
  
  return IDL.Service({
    'addArtist' : IDL.Func([Artist], [IDL.Nat], []),
    'addArtwork' : IDL.Func([Artwork], [IDL.Nat], []),
    'addExhibition' : IDL.Func([Exhibition], [IDL.Nat], []),
    'getAllArtists' : IDL.Func([], [IDL.Vec(Artist)], ['query']),
    'getAllArtworks' : IDL.Func([], [IDL.Vec(Artwork)], ['query']),
    'getAllExhibitions' : IDL.Func([], [IDL.Vec(Exhibition)], ['query']),
    'getAllExhibitionsSortedByDate' : IDL.Func(
        [],
        [IDL.Vec(Exhibition)],
        ['query'],
      ),
    'getArtist' : IDL.Func([IDL.Nat], [Artist], ['query']),
    'getArtwork' : IDL.Func([IDL.Nat], [Artwork], ['query']),
    'getExhibition' : IDL.Func([IDL.Nat], [Exhibition], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };