/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artist {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'photoUrl' : string,
  'specialty' : string,
}
export interface Artwork {
  'id' : bigint,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'imageUrl' : string,
  'artist' : string,
  'medium' : string,
}
export interface Exhibition {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'description' : string,
  'imageUrl' : string,
  'location' : string,
  'startDate' : Time,
}
export type Time = bigint;
export interface _SERVICE {
  'addArtist' : ActorMethod<[Artist], bigint>,
  'addArtwork' : ActorMethod<[Artwork], bigint>,
  'addExhibition' : ActorMethod<[Exhibition], bigint>,
  'getAllArtists' : ActorMethod<[], Array<Artist>>,
  'getAllArtworks' : ActorMethod<[], Array<Artwork>>,
  'getAllExhibitions' : ActorMethod<[], Array<Exhibition>>,
  'getAllExhibitionsSortedByDate' : ActorMethod<[], Array<Exhibition>>,
  'getArtist' : ActorMethod<[bigint], Artist>,
  'getArtwork' : ActorMethod<[bigint], Artwork>,
  'getExhibition' : ActorMethod<[bigint], Exhibition>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];